#!/hint/sh

# Define additional functionality for pinentry. For example
command -v pinentry-gnome3 >/dev/null 2>&1 && exec pinentry-gnome3 "$@"
#test -e /usr/lib/libQt5Widgets.so.5 && exec /usr/bin/pinentry-qt     "$@"
